version: "3.6"
services:
  redis:
    image: "redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
  web:
    build: .
    links:
      - "redis:redis"
    depends_on:
      - "redis"
    restart: on-failure
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./webapp:/opt/webapp
